development:
  telegram:
    default: 
      token: 603753108:AAFiwXEUkVjGYdM0A1T3CBqL06-Lk6-IyZ0
      username: articles_directory_bot
production:
  secret_key_base: 8e68125fa1ec1554da52c97c884df882b77fba0a15e670842eb99774c57334e9368a115142df09d548edb3e9a05dfe26b2d11c9c642ed83cb2e91f2ef1272f3d
